OpenZeppelin/contracts-wizard

packages/ui/src/App.svelte
packages/ui/src/styles/global.css
packages/ui/src/styles/reset.css
packages/ui/src/utils/inject-hyperlinks.ts

Turns import statements into hyperlinks to the corresponding contract source code on GitHub.
Links to source code rather than docs site for the following reasons:
- Import text should be the hyperlink itself, so only one set of links can be provided (either source or docs but not both)
- Developers using a parent contract may want to see how it was written, so are probably interested in the source
- Each feature's tooltip already has a Read More link that goes to the docs
- If Upgradeability is enabled, the links point to source in [contracts-upgradable](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/) so developers can see the initializer functions

Link to contract source from imports

---

packages/ui/src/ERC1155Controls.svelte
packages/ui/src/ERC20Controls.svelte
packages/ui/src/ERC721Controls.svelte

Links to Pausable are currently pointing to https://docs.openzeppelin.com/contracts/4.x/api/utils#Pausable, which appears to have been moved to https://docs.openzeppelin.com/contracts/4.x/api/security#Pausable.
This PR updates those links.

Update links to Pausable

---

packages/ui/src/cairo/UpgradeabilitySection.svelte
packages/ui/src/inputs/ToggleRadio.svelte

Under Upgradeability section, add a UUPS radio button as the only option.
This affects the UI only.  The API for `upgradeable` option will remain as `false | true` to remain backward compatible.

Cairo - Add UUPS radio button

---

README.md
packages/core-cairo/README.md
packages/core/README.md

Add npm badges for wizard and wizard-cairo
Colors are based on css for the titles [here](https://github.com/OpenZeppelin/contracts-wizard/blob/master/packages/ui/public/standalone.css#L64) and [here](https://github.com/OpenZeppelin/contracts-wizard/blob/master/packages/ui/public/standalone.css#L79)

Add npm badges

---

packages/ui/src/AccessControlSection.svelte

Fixes #152 
If `access` should be implied (e.g. `required` is true), then set it to be enabled regardless of whether it was previously implied (e.g. regardless of `wasRequired`)

Fix access checkbox when implied by default

---

packages/ui/src/App.svelte
packages/ui/src/remix.ts

As the [Remix release v0.25.1](https://github.com/ethereum/remix-project/releases/tag/v0.25.1) added the `deployProxy` query parameter to auto enable the UUPS contracts deploy proxy.  As described by @htadashi on https://github.com/OpenZeppelin/contracts-wizard/issues/155:
> the warning tooltip introduced in https://github.com/OpenZeppelin/contracts-wizard/issues/63 can be removed  if the UUPS option is selected.
Note: Remix added support for UUPS only and the warning can be removed in this case, although the transparent upgradeability will still need to show the warning.
Closes #155

Remove Upgradable Contracts Warnings for Remix

---

packages/ui/src/ERC20Controls.svelte

[`EIP-2612`](https://eips.ethereum.org/EIPS/eip-2612) is final now.

Remove draft hint for `permit` `ERC-20` function

---

packages/ui/rollup.config.mjs

Adding option to proc.spawn to fix bug on windows, this should fix the behaviour on windows but it will not affect non windows environments, this fix #229 issue

Error: spawn yarn ENOENT

---

packages/ui/src/utils/inject-hyperlinks.ts

The code to inject hyperlinks can be "hijacked" in the sense that a string like `@openzeppelin/contracts/../../../../xyz` will produce an unintended link to another location. In combination with the ability to put in an arbitrary value in the name field, using the above string as name currently results in some bad HTML output.
This PR attempts to make link injection more robust by 1) preventing paths that contain `/../`, and 2) using non-greedy matching in the regular expression.

Prevent hijacking of link injection

---

packages/core/CHANGELOG.md
packages/core/src/governor.test.ts
packages/core/src/governor.ts

Change default voting delay from 1 block to 1 day.

Change default voting delay for Governor

---

.github/workflows/test.yml
packages/core/src/zip-hardhat.test.ts

Test with Node 18 as it is the current minimum supported LTS version. 
Closes #299

Use actions v4 and Node 18 for tests

---

packages/core-cairo/src/index.ts
packages/core/src/index.ts
packages/ui/package.json
packages/ui/src/UnsupportedVersion.svelte
packages/ui/src/embed.ts
packages/ui/src/main.ts
packages/ui/src/post-message.ts

In our documentation sites, we embed Wizard for different versions of the Contracts libraries, for example on https://docs.openzeppelin.com/contracts-cairo/0.9.0/wizard
However, Wizard is only compatible with specific versions of the libraries, which is specified (and shown on Wizard) as a semantic version string.
In the embeddings, we should allow passing through a `version` parameter for the selected version of the documentation.  If this version is outside of the compatible versions, the embed will show an error page instead of the actual Wizard.  By doing this, we will no longer need to manually remove Wizard from older versions of the doc sites.
This version can be passed in from a documentation page like this:
```
<oz-wizard style="display: block; min-height: 40rem;" …
```

Show error page if embed version out of supported range

---

packages/ui/package.json
packages/ui/src/post-config.ts
yarn.lock

This dependency does not seem to be used, so it can be removed.
Replaces / Closes https://github.com/OpenZeppelin/contracts-wizard/pull/365

Remove uuid dependency from UI

---

packages/ui/src/App.svelte
packages/ui/src/cairo/App.svelte
packages/ui/src/embed.ts
packages/ui/src/initial-options.ts
packages/ui/src/main.ts

Enables the `name`, `symbol`, and `premint` options to be prefilled from URL search parameters.
Previously the string content after `#` in the URL was treated as the tab (e.g. `erc20` or `erc721`)
With this PR, it splits that string content into further fragments, where a fragment can be just the tab as before, or fragments can be additional `key=value` pairs.
For example: https://wizard.openzeppelin.com/cairo#erc721&name=MyContractName would go to the Cairo language with `tab=erc721` and `name=MyContractName`

Enable prefilling initial options from URL search parameters

---

.github/workflows/test.yml

#404 added the git repository https://github.com/OpenZeppelin/openzeppelin-community-contracts/ as a dependency.  This caused the test builds to encounter issue https://github.com/yarnpkg/yarn/issues/7212.
As a workaround, as described in a comment in that yarn issue, we can use `yarn install --network-concurrency 1`.
This can be reverted when we release https://github.com/OpenZeppelin/openzeppelin-community-contracts/ as an NPM package and switch the dependency to use that.

Fix build for tests

---

packages/ui/src/App.svelte

Prevent line wrapping from whitespace in contract type labels.  This ensures the button labels are all single line.
Related to #404

Prevent line breaks in labels

---

packages/ui/api/ai.ts
packages/ui/src/Wiz.svelte
packages/ui/src/wiz-functions.ts

Update AI assistant for stablecoin and real world asset

---

packages/ui/src/utils/inject-hyperlinks.ts

Add hyperlinks for imports from Community Contracts

---

NOTICE
packages/core-cairo/CHANGELOG.md
packages/core-cairo/NOTICE
packages/core-cairo/README.md
packages/core-cairo/src/api.ts
packages/core-cairo/src/governor.ts
packages/core-cairo/src/vesting.test.ts
packages/core-cairo/src/vesting.ts
packages/core/NOTICE
packages/ui/public/cairo.html
packages/ui/public/index.html

- Removes the `isAccessControlRequired` function from the APIs for `governor` and `vesting` by separating their interfaces from contracts that have access control options.
- Although `account`, `governor`, and `vesting` have their own ways of handling access control, they don't require this function because it's only purpose was to allow the caller to inspect the default behavior of the `access` option.
- Update Cairo API readme.
- Updates copyright year in preparation for publishing.

Remove `isAccessControlRequired` from specific contract APIs, update copyright year

---

packages/ui/src/cairo/inject-hyperlinks.ts

- If multiple components are imported, link to the parent .cairo file with the same name as the last path segment
- If a single component is imported, link to the file containing the component (if defined in the known mappings), otherwise link to the parent .cairo file with the same name as the last path segment
Fixes #423

Add Cairo links when multiple components are imported

---

packages/core-cairo/CHANGELOG.md
packages/core-cairo/package.json
packages/core-cairo/src/print.ts
packages/core-cairo/src/utils/format-lines.ts
packages/core/CHANGELOG.md
packages/core/hardhat.config.js
packages/core/package.json
packages/core/src/print.ts
packages/core/src/utils/format-lines.ts
yarn.lock

- Removes `array.prototype.flatmap` and `array.prototype.flat` since `flat` and `flatMap` are now supported in current LTS versions of Node JS.
- Removes unused `bn.js` and `ethereum-cryptography` from Cairo Wizard package.

Remove unused dependencies

---

packages/ui/src/embed.ts

Resolves https://github.com/OpenZeppelin/contracts-wizard/issues/295
As per [Mozilla's Clipboard API docs](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API#security_considerations):
> Chromium browsers:
> ...
>    - The HTTP [Permissions-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy) permissions clipboard-read and clipboard-write must be allowed for [<iframe>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) elements that access the clipboard.
I verified this is the probable root of the issue by doing the following:
- open _packages/ui/public/index.html_
- comment out `div class="wizard-container"` which includes the nested `oz-wizard` component
- below it, paste the exact `iframe` code that's injected into [the docs …

Append `allow="clipboard-write"` to wizard embed iframe

---

packages/ui/src/solidity/App.svelte
packages/ui/src/solidity/ERC20Controls.svelte
packages/ui/src/solidity/RealWorldAssetControls.svelte
packages/ui/src/solidity/StablecoinControls.svelte

Chain ID is required when using Premint with Cross-Chain Bridging.  The Chain ID field is in the ERC20 tab but missing from Stablecoin and RWA tabs.

Add premint chainId to Stablecoin and RWA tabs

---

packages/ui/src/solidity/App.svelte

This PR fixes #466  in Safari browsers where the code preview would display incorrect or partially cached content when:
1. Switching between tabs (e.g., from ERC20 to Stablecoin)
2. Scrolling horizontally to view the full code
3. Changing contract settings
The issue was caused by Safari's rendering engine not properly repainting/reflowing the code preview container when content changes occurred in combination with horizontal scrolling. This resulted in showing stale or mixed content from previous states.
Fix:
- Added a force re-render mechanism that temporarily removes and re-adds the code preview element
- Applied the fix to both tab changes and contract option updates
- Set minimal timeout (0ms) to ensure the DOM has a chance to properly clear before re-rendering
The actual contract …

fix: Safari rendering issues with code preview when switching tabs or scrolling

---

packages/ui/src/cairo/App.svelte
packages/ui/src/cairo_alpha/App.svelte
packages/ui/src/solidity/App.svelte
packages/ui/src/stellar/App.svelte
packages/ui/src/stylus/App.svelte

- Apply https://github.com/OpenZeppelin/contracts-wizard/pull/495 to `cairo_alpha` UI
- Fixes extra whitespace in UI before the contract code, due to whitespace in the `<code>` tag which caused it to look like:

Fix spacing in UI code display

---

CONTRIBUTING.md
packages/ui/src/main.ts
packages/ui/src/solidity/App.svelte

**Description:**
This pull request addresses several typos found in the documentation and codebase:
1. **CONTRIBUTING.md:**
- Corrected the spelling of "formater" to "formatter."
2. **packages/ui/src/main.ts:**
- Fixed the function name from "evalutateSelection" to "evaluateSelection."
3. **packages/ui/src/solidify/App.svelte:**
- Corrected the function name from "getButtonVisiblities" to "getButtonVisibilities."
These changes improve code readability and maintain consistency across the project.

 Fix Typos in Documentation and Code

---

packages/ui/src/solidity/DefenderDeployModal.svelte

Related to https://github.com/OpenZeppelin/defender-deploy-plugin/pull/55
This PR ensures that the referrer origin is always available (without requiring the full URL), including for cross-origin requests.
This isn't strictly needed since browser defaults currently work, but this sets this explicitly since https://github.com/OpenZeppelin/defender-deploy-plugin/pull/55 relies on this use case.

Add origin referrer for Defender Deploy

---

packages/core/solidity/src/account.ts

Fixed a typo in a comment in account.ts where "Dissambiguate" was incorrectly spelled. Changed to the correct spelling "Disambiguate".
File changed:
- packages/core/solidity/src/account.ts

Fix typo in comment: "Dissambiguate" -> "Disambiguate"

---

.github/workflows/version.yml

If only the UI package was changed, ignore the version workflow which updates the Prepare Release PR since the core packages don't need to be released.

Ignore version workflow if only UI changes present

---

packages/core/solidity/src/account.ts

Description:  
This pull request corrects a typo in the comment within the account.ts file, changing "Dissambiguate" to the correct spelling "Disambiguate" between Signer and AccountERC7579. No functional code changes were made; this update is for clarity and consistency in documentation.

Fix Typo: Change "Dissambiguate" to "Disambiguate" in account.ts

---

CONTRIBUTING.md
README.md

Reorganizes the readme to describe more general usage first, then contribution details and license info to more closely match with our other open source repos.

Reorganize readme

---

packages/ui/src/cairo/App.svelte
packages/ui/src/cairo_alpha/App.svelte
packages/ui/src/common/HelpTooltip.svelte
packages/ui/src/common/ParentExpandableSection.svelte
packages/ui/src/solidity/App.svelte
packages/ui/src/stellar/App.svelte
packages/ui/src/stylus/App.svelte

In some contexts is convenient to change the width of the controls.
https://github.com/user-attachments/assets/ce019b23-d946-4c08-abd3-6874695441cc

Allow resizing controls
