- packages/ui/public/index.html
New compatibility means new text.
closes #85
> Update Wizard compatibility 

- packages/ui/src/App.svelte
> Fix spacing within pre statement

- packages/core/src/governor.ts
- packages/ui/src/GovernorControls.svelte
Part of https://github.com/OpenZeppelin/contracts-wizard/issues/101
> Mention ERC721 in governor votes

- .github/workflows/test.yml
Add steps to compile and test `cairo-core`
> Add Cairo to GitHub actions

- README.md
closes #214 
- Added a link to the `readme` image.
> Link readme image to URL.

- packages/core/CHANGELOG.md
- packages/core/src/print-versioned.ts
> Remove unspecified dependency on @openzeppelin/contracts

- packages/core/CHANGELOG.md
- packages/core/package.json
> Fix missing file

- packages/ui/public/index.html
Verified using https://www.opengraph.xyz/url/https%3A%2F%2Fmaster--bespoke-queijadas-16c241.netlify.app%2F
> Add metadata

- README.md
Can be useful to see the deployment status.
> Add Netlify badge in readme

- packages/ui/src/App.svelte
There is a configuration issue with Wizard AI, so temporarily disabling the AI popup until it is fixed.
> Temporarily disable Wizard AI

- packages/ui/api/ai.ts
Adds logging when an error occurs in the AI assistant function, so that the error details are sent to the edge function logs.
> Add logging to edge function

- packages/ui/src/wiz-functions.ts
Enables the AI assistant to make use of new options introduced in #347
> Add clock mode options to AI assistant

- packages/ui/src/cairo/inject-hyperlinks.ts
> Fix cairo hyperlinks

- packages/ui/src/cairo/ERC20Controls.svelte
- packages/ui/src/cairo/ERC721Controls.svelte
> Fix ERC20 Votes - Broken link in 'Read More'

- .github/workflows/cla.yml
- Add CLA workflow permission for contribution
> feat: Add CLA workflow for contributions

- packages/core/stylus/CHANGELOG.md
- packages/core/stylus/package.json
Updates changelog and version number for publishing.
> Publish @openzeppelin/wizard-stylus@0.2.0-alpha.4

- .github/workflows/cla.yml
> fix: PR Sign Comment

- .github/workflows/cla.yml
> fix: Condition messaging

- packages/core/solidity/CHANGELOG.md
- packages/core/solidity/package.json
> bump version for publish

- packages/ui/src/common/Wiz.svelte
- packages/ui/src/embed.ts
- packages/ui/src/standalone.css
Fixes #524 
The AI button was getting cutoff in different screen sizes so I adjusted the value so that it would be there regardless of the screen sizes thus improving ux
> feat: positioned the assistant button in such a way that it wont be affected in different screen sizes

- .github/workflows/test.yml
Adds MCP tests to the Github workflow.
> Add MCP to test workflow

- .changeset/clever-geese-follow.md
- packages/mcp/package.json
Use latest Wizard API versions.
> Update MCP dependencies
